import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";

const jetBrainsMono = JetBrains_Mono({ subsets: ["latin"],
  weight:["100", "200", "300", "400", "500","600"]
 });

export const metadata: Metadata = {
  title: "Game Experience",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jetBrainsMono.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
